config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'cars#index'
  resources :cars, only: [:index, :show, :create, :new] do
    resources :bookings, only: :create
    resources :reviews, only: :create
  end
  resources :bookings, only: [:show, :destroy, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :car
  validates :start_date, :end_date, presence: true
  # validate :start_date_cannot_be_in_the_past
  # validate :end_date_must_be_after_start_date
#
  def start_date_cannot_be_in_the_past
    errors.add(:start_date, "can't be in the past") if
      self.start_date <= Date.today
  end

  def end_date_must_be_after_start_date
    errors.add(:end_date, "must be after start date") if
    self.end_date < self.start_date
  end

  def rental_days
    (self.end_date-self.start_date).to_i
  end
end

app/models/car.rb
class Car < ApplicationRecord
  has_one_attached :photo
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :users, through: :bookings
  has_many :reviews, dependent: :destroy
  validates :capacity, :brand, :kind, :price, :drive_train, presence: true
  geocoded_by :location
  validate :photo_validate
  after_validation :geocode, if: :will_save_change_to_location?

  def self.brands
    @cars = Car.all
    brands = @cars.map { |car| car.brand }
    return brands
  end

  def self.kinds
    @cars = Car.all
    kinds = @cars.map { |car| car.kind }
    return kinds
  end

  def unavailable_dates
    bookings.pluck(:start_date, :end_date).map do |range|
      { from: range[0], to: range[1] }
    end
  end

  def photo_validate
    if photo.attached? == false
      errors.add(:photo, 'is required')
    end
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :car
  belongs_to :user
  validates :content, presence: true
  validates :content, length: { minimum: 15 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings
  has_many :reviews
  has_many :cars
  has_one_attached :photo
  validates :first_name, :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    # devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end


  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_car, except: [:destroy, :show, :index]

  def index
    @bookings = policy_scope(Booking)
    @bookings = current_user.bookings
  end

  def create
    @booking = Booking.new(set_params)
    @review = Review.new
    @booking.car = @car
    @booking.user = current_user
    authorize @booking
    if @booking.save
      redirect_to booking_path(@booking)
    else
      render 'cars/show'
    end
  end

  def show
    @booking = Booking.find(params[:id])
    authorize @booking
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    authorize @booking
    redirect_to bookings_path, notice: 'Booking was successfully canceled'
  end

  private

  def set_car
    @car = Car.find(params[:car_id])
  end

  def set_params
    params[:booking].permit(:start_date, :end_date)
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
skip_before_action :authenticate_user!, only: [:index, :show]

  def index
  @cars = policy_scope(Car).geocoded
   if params[:query].present?
    @cars = Car.near(params[:query])
   else
     @cars
   end
  @markers = @cars.map do |car|
    {
      lat: car.latitude,
      lng: car.longitude,
      infoWindow: render_to_string(partial: "info_window", locals: { car: car })
    }
    end
  end

  def new
    @kinds = ["Crew Cab Pickup", "Coupe", "Sedan", "Regular Cab Pickup", "Wagon", "Cargo Van", "SUV", "Minivan", "Hatchback", "Passenger Van", "Extended Cab Pickup", "Convertible"]
    @drive_train_types = ["Automanual", "Automatic", "CVT", "Manual"]
    @car = Car.new
    authorize @car
  end

  def create
    @car = Car.new(set_car_params)
    @car.user_id = current_user.id
    authorize @car
    if @car.save
      redirect_to car_path(@car)
    else
      render :new
    end
  end

  def show
    @booking = Booking.new
    @car = Car.find(params[:id])
    @review = Review.new
    authorize @car
  end

  private

  def set_car_params
    params[:car].permit(:kind, :brand, :capacity, :price, :drive_train, :location, :description, :photo, :user_id)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @booking = Booking.new
    @car = Car.find(params[:car_id])
    @review = Review.new(review_params)
    @review.car = @car
    @review.user_id = current_user.id
    authorize @review
   if @review.save
    # The code below alows to append messages to review with or without JS enabled
      respond_to do |format|
        format.html { redirect_to car_path(@car) }
        format.js  # <-- will render `app/views/reviews/create.js.erb`
      end
    else
      respond_to do |format|
        format.html { render 'cars/show' }
        format.js  # <-- idem
      end
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<div id='car-booking-dates' data-unavailable="<%= @car.unavailable_dates.to_json %>">
   <%= simple_form_for([@car, @booking]) do |f| %>
       <%= f.input :start_date, as: :string, placeholder: "Please enter a start date", input_html: { class: "range_date", id: "booking_start_date"} %>
       <%= f.input :end_date, as: :string, placeholder: "Please enter an end date", input_html: { class: "range_date", id: "booking_end_date"} %>
       <%= f.submit "Confirm", class: "btn btn-primary" %>
       <%= f.error_notification %>
    <% end %>
 </div>

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/destroy.html.erb
<h1>Bookings#destroy</h1>
<p>Find me in app/views/bookings/destroy.html.erb</p>

app/views/bookings/index.html.erb
<div class="container">
  <h1>My Bookings</h1>
  <% if @bookings.present? %>
    <div class="cards">
      <% @bookings.each do |booking| %>
        <div class="car-card">
          <%= cl_image_tag booking.car.photo.key, height: 300, width: 400%>
          <div class="car-card-info">
            <div class="left-side">
              <h2><%= booking.car.brand %></h2>
              <p>Rental Period: <%= booking.rental_days %> days</p>
              <p>Start date: <%=  booking.start_date.to_time.strftime('%e/%m/%y')%></p>
              <p>End date: <%=  booking.end_date.to_time.strftime('%e/%m/%y')%></p>
            </div>
            <div class="right-side-for-bookings">
               <u><%= link_to "Show booking details", booking_path(booking) %> </u>
                <%= link_to "Cancel booking", booking_path(booking), method: :delete, data: { confirm: "Are you sure?" }, class: "cancel-btn" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <h1 id="no-results">Sorry, you have no bookings.</h1>
  <% end %>
</div>

app/views/bookings/show.html.erb
<div class="container">
  <div class="car-info row">
    <div class="car-details col-md-8 ">
      <h1 id="booking-title">Booking confirmation: <strong><%= @booking.car.brand%> <%=  @booking.car.kind  %></strong></h1>
      <p>Congratulations! Your booking is complete. <br> Please check if all information in the box to the right is correct.</p>
      <%= cl_image_tag @booking.car.photo.key, height: 300, width: 500, id: "img-booking"%>
    </div>
    <div class="booking-status col-md-4 position-sticky ">
      <div class="booking-status-title">
        <h4 class="border-bottom"><strong>Booking details</strong>  </h4>
      </div>
      <div class="booking-status-info">
        <p>Rental period: <%= @booking.rental_days %> days</p>
        <p>Start date: <%= @booking.start_date.to_time.strftime('%e/%m/%y')%></p>
        <p>End date: <%= @booking.end_date.to_time.strftime('%e/%m/%y')%></p>
        <p>Pick up location <%= @booking.car.location %></p>
      </div>
      <div class="total-price border-top">
        <p class="booking-status-price"><strong>Total amount:  <%= (@booking.car.price * @booking.rental_days) %>€</strong></p>
      </div>
      <div class="btn-red">
        <%= link_to "Go to my bookings", bookings_path, class: "submit-search-button"%>
      </div>
    </div>
  </div>
</div>

app/views/cars/_form.html.erb
<%= simple_form_for(@car) do |f| %>
  <%= f.input :kind, collection: @kinds %>
  <%= f.input :brand %>
  <%= f.input :capacity %>
  <%= f.input :price %>
  <%= f.input :drive_train, collection: @drive_train_types %>
  <%= f.input :location %>
  <%= f.input :description %>
  <%= f.input :photo, as: :file %>
  <%= f.submit "Host your car", class: "btn btn-primary" %>
<% end %>

app/views/cars/_info_window.html.erb
<h4 class="car-title-map-popup" style="border-bottom: 1px solid lightgrey;"><%= link_to car.brand, car_path(car)%></h4>
<p><i class="fas fa-money-bill-wave"></i> <%= car.price %> per day</p>
<p><i class="fas fa-user"></i> <%= car.capacity %></p>
<p>🕹 <%= car.drive_train %></p>

app/views/cars/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://source.unsplash.com/axTvnbgRlAk);">
  <div class="container">
    <h1>Book a car of <strong>your dream</strong>!</h1>
    <p>Select from awesome collection of unique cars</p>
  </div>
</div>

<div class="container">
  <% if @cars.present? %>
      <% grouped_cars = @cars.group_by{|car| car.kind} %>
      <% grouped_cars.each do |car_kind, cars| %>
        <div class="car-category">
          <h2><%= car_kind %></h2>
          <div class="cards">
            <% cars.each do |car| %>
              <div class="car-card">
                <%= cl_image_tag car.photo.key, height: 300, width: 400 %>
                <div class="car-card-info">
                  <div class="left-side">
                    <h2><%= car.brand %></h2>
                    <p>👤 <%= car.capacity %></p>
                    <p>🕹 <%= car.drive_train %></p>
                  </div>
                  <div class="right-side">
                    <h2 class="car-card-pricing">Price/day: <%= car.price %>€</h2>
                    <%= link_to "More details", car_path(car), class: "submit-search-button" %>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
  <% else %>
    <h1 id="no-results">Sorry, we didn't find any cars matching your search</h1>
  <% end %>
  <h2>View cars on map</h2>
  <div
    id="map"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
  ></div>
</div>

app/views/cars/new.html.erb
<div class="container create">
  <h1>Host your car</h1>
  <%= render 'form', car: @car %>
</div>

app/views/cars/show.html.erb
<div class="container">
  <div class="wrapper">
    <div class="car-details">
      <h1 id="booking-title"><strong><%= @car.brand%> <%=  @car.kind  %></strong></h1>
        <%= cl_image_tag @car.photo.key, height: 300, width: 500, crop: :fill, id: "img-car" %>
    </div>
    <div class="booking-status-box">
      <div class="booking-status-box-title">
        <h4 ><strong>Details</strong>  </h4>
        <p class="border-bottom"></p>
      </div>
      <div class="booking-status-info">
        <p>Price €<%= @car.price %> per day</p></p>
        <p>Pick up location <%= @car.location %></p>
        <% if @car.online %>
          <i class="fas fa-car green"> - available</i>
        <% else %>
          <i class="fas fa-car red"> - unavailable</i>
        <% end %>
      </div>
      <% if user_signed_in? %>
        <% if current_user.id != @car.user_id %>
        <div class="button-collapse">
           <a class="booking-book-button " data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
           Book this car </a>

        <div class="collapse" id="collapseExample">
          <div class="card card-body">
            <%= render "bookings/form" %>
          </div>
        </div>
        <% end %>
      <% end %>

      </div>
    </div>

    <div class="description-text">
      <h4><strong>Description</strong></h4>
      <p><%= @car.description %> </p>
    </div>
    <div class="review-text">
      <h4 id="review-count">Reviews: <%= @car.reviews.size%></h4>
    <div id="reviews">
      <% if @car.reviews.blank? %>
        <span id="hide-help">Be the first to leave a review for <strong><%= @car.brand %></strong></span>
      <% else %>
        <% @car.reviews.each do |review| %>
          <%= render 'reviews/show', review: review %>
        <% end %>
      <% end %>
    </div>
    <div class="review-button col-md-8">
      <%= render 'reviews/form', car: @car, review: @review%>
    </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= favicon_link_tag asset_path('favicon.ico') %>
    <title>Cars BnB</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>

  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/reviews/_form.html.erb
<%= simple_form_for([ car, review ], remote: true) do |form| %>
  <%= form.input :content, as: :text, class: "review-text-input" %>
  <%= form.input :rating, collection: (0..5), class: "review-rating-input" %>
  <%= form.button :submit, class: "booking-book-button" %>
<% end %>

app/views/reviews/_show.html.erb
<div class="card-review">
  <%= cl_image_tag review.user.photo.key, class: 'avatar card-review-avatar' %>
  <p class="card-review-time">Created on: <%= review.created_at.to_time.strftime('%e/%m/%y') %></p>
  <p class="card-review-star"> <%= '⭐' * review.rating %> </p>
  <p class="card-review-content"><%= review.content %></p>
</div>

app/views/reviews/create.js.erb
var reviewForm = document.getElementById('new_review');

<% if @review.persisted? %>

// Step 1 create the html for the review
var newReview = "<%= j render 'reviews/show', review: @review %>";

// Step 2 append the new review to the list
var reviews = document.getElementById('reviews');
reviews.insertAdjacentHTML('beforeend', newReview);
document.getElementById('review-count').innerText = 'Number of reviews: <%= @car.reviews.size%>';
// Step 3 Empty out the input box
reviewForm.innerHTML = "<%= j render 'reviews/form', car: @car, review: Review.new %>";
document.getElementById('hide-help').remove();
<% else %>
// 1. render the form partial with the new @review
reviewForm.innerHTML = "<%= j render 'reviews/form', car: @car, review: @review %>";

<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div></div>
  <div class="footer-links">
    <a href="#">Contact</a>
    <a href="#">Email</a>
    <a href="#">FAQ</a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light sticky-top navbar-lewagon">

  <%= link_to cars_path, class: "navbar-brand" do %>

    <img src="http://cdn.onlinewebfonts.com/svg/img_23163.svg" class="filter-red">
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class ="navbar-search">
    <div class="navbar-search-field">
      <%= form_tag cars_path, method: :get do %>
        <%= text_field_tag :query, params[:query], class: "form-control search-input", placeholder: "Search locations"%>
    </div>
    <div class="navbar-submit-field">
      <%= submit_tag "Search", class: "submit-search-button"%>
      <% end %>
    </div>
  </div>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          Welcome, <%= current_user.first_name.capitalize %>
        </li>
        <li class="nav-item dropdown">
          <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My bookings", bookings_path, class: "dropdown-item" %>
            <%= link_to "Host your car", new_car_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>

    </ul>
  </div>
</div>